export const CALENDAR_CREATE_REMINDER = 'CALENDAR_CREATE_REMINDER';
export const CALENDAR_UPDATE_REMINDER = 'CALENDAR_UPDATE_REMINDER';
export const CALENDAR_DELETE_REMINDER = 'CALENDAR_DELETE_REMINDER';
export const CALENDAR_NAV_PREV_MONTH = 'CALENDAR_NAV_PREV_MONTH';
export const CALENDAR_NAV_NEXT_MONTH = 'CALENDAR_NAV_NEXT_MONTH';
